create table audit_log (
   log_id         number generated by default as identity primary key,
   table_name     varchar2(50) not null,
   operation_type varchar2(20) check ( operation_type in ( 'INSERT',
                                                           'UPDATE',
                                                           'DELETE' ) ),
   record_id      number,
   old_value      varchar2(4000),
   new_value      varchar2(4000),
   changed_by     varchar2(50),
   change_date    date default sysdate
);