create table parking_lots (
   lot_id       number generated by default as identity primary key,
   lot_name     varchar2(100) not null,
   location     varchar2(150) not null,
   total_slots  number check ( total_slots > 0 ),
   status       varchar2(20) default 'Open' check ( status in ( 'Open',
                                                          'Closed',
                                                          'Maintenance' ) ),
   created_date date default sysdate
);