create table parking_sessions (
   session_id     number generated by default as identity primary key,
   slot_id        number not null,
   vehicle_id     number not null,
   entry_time     date default sysdate,
   exit_time      date,
   session_status varchar2(20) default 'Active' check ( session_status in ( 'Active',
                                                                            'Completed',
                                                                            'Cancelled' ) ),
   parking_fee    number(7,2),
   constraint fk_slot foreign key ( slot_id )
      references parking_slots ( slot_id )
         on delete cascade,
   constraint fk_vehicle foreign key ( vehicle_id )
      references vehicles ( vehicle_id )
         on delete cascade
);