create table parking_slots (
   slot_id     number generated by default as identity primary key,
   lot_id      number not null,
   slot_number varchar2(10) not null,
   slot_type   varchar2(20) default 'Regular' check ( slot_type in ( 'Regular',
                                                                   'Compact',
                                                                   'Large',
                                                                   'Handicap' ) ),
   floor_level number default 1,
   status      varchar2(20) default 'Available' check ( status in ( 'Available',
                                                               'Occupied',
                                                               'Reserved' ) ),
   hourly_rate number(6,2) default 2.50,
   constraint fk_lot foreign key ( lot_id )
      references parking_lots ( lot_id )
         on delete cascade
);