create table payments (
   payment_id       number generated by default as identity primary key,
   session_id       number not null,
   amount           number(7,2) not null,
   payment_method   varchar2(20) default 'Cash' check ( payment_method in ( 'Cash',
                                                                          'Card',
                                                                          'MobilePay' ) ),
   payment_date     date default sysdate,
   transaction_ref  varchar2(50),
   discount_applied number(5,2) default 0,
   constraint fk_session foreign key ( session_id )
      references parking_sessions ( session_id )
         on delete cascade
);