create table reservations (
   reservation_id   number generated by default as identity primary key,
   vehicle_id       number not null,
   slot_id          number not null,
   reservation_time date default sysdate,
   reserved_from    date,
   reserved_until   date,
   status           varchar2(20) default 'Pending' check ( status in ( 'Pending',
                                                             'Confirmed',
                                                             'Cancelled' ) ),
   constraint fk_res_vehicle foreign key ( vehicle_id )
      references vehicles ( vehicle_id )
         on delete cascade,
   constraint fk_res_slot foreign key ( slot_id )
      references parking_slots ( slot_id )
         on delete cascade
);