CREATE TABLE VEHICLES (
    vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR2(20) UNIQUE NOT NULL,
    vehicle_type VARCHAR2(20) CHECK (vehicle_type IN ('Car','Motorbike','Truck','Bus')),
    owner_name VARCHAR2(100),
    owner_contact VARCHAR2(20),
    is_frequent CHAR(1) DEFAULT 'N' CHECK (is_frequent IN ('Y','N'))
);
